// This file will be auto-generated by Supabase CLI
// For now, we define a placeholder type that will be replaced

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          role: 'buyer' | 'vendor' | 'admin';
          is_active: boolean;
          two_factor_enabled: boolean;
          preferred_currency: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          role?: 'buyer' | 'vendor' | 'admin';
          is_active?: boolean;
          two_factor_enabled?: boolean;
          preferred_currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          role?: 'buyer' | 'vendor' | 'admin';
          is_active?: boolean;
          two_factor_enabled?: boolean;
          preferred_currency?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      vendors: {
        Row: {
          id: string;
          user_id: string;
          store_name: string;
          store_description: string | null;
          logo_url: string | null;
          banner_url: string | null;
          is_verified: boolean;
          status: 'pending' | 'approved' | 'rejected' | 'suspended';
          social_links: Json;
          created_at: string;
          updated_a